let w=600,h=400;let pw=10,ph=80;let playerX=10,playerY=0;let cpuX=0,cpuY=0;let playerSpeed=6,cpuMaxSpeed=5;let ballR=8;let ballX=0,ballY=0,ballVX=0,ballVY=0;let ballHue=0,ballSat=100;let scoreP=0,scoreC=0;let cpuMissCounter=0,cpuMissTargetY=0;let initialVX=4,initialVY=3;let maxSpeed=10,minSat=20;let restitution=1.3;
function setup(){createCanvas(w,h);colorMode(HSB,360,100,100);playerY=(h-ph)/2;cpuX=w-10-pw;cpuY=(h-ph)/2;ballX=w/2;ballY=h/2;ballVX=initialVX;ballVY=initialVY;ballHue=random(0,360);let s=Math.sqrt(ballVX*ballVX+ballVY*ballVY);ballSat=constrain(map(s,0,maxSpeed,minSat,100),minSat,100);textAlign(CENTER);textSize(32);} 
function resetBall(){ballX=w/2;ballY=h/2;let sx=random()<0.5?-1:1;ballVX=initialVX*sx;let sy=random()<0.5?-1:1;ballVY=initialVY*sy;ballHue=random(0,360);let s=Math.sqrt(ballVX*ballVX+ballVY*ballVY);ballSat=constrain(map(s,0,maxSpeed,minSat,100),minSat,100);} 
function handleInput(){if(keyIsDown(UP_ARROW)){playerY-=playerSpeed;}if(keyIsDown(DOWN_ARROW)){playerY+=playerSpeed;}playerY=constrain(playerY,0,h-ph);} 
function updateCPU(){if(cpuMissCounter===0){if(random()<0.01){cpuMissCounter=30;cpuMissTargetY=random(ph/2,h-ph/2);}}let targetY=cpuMissCounter>0?cpuMissTargetY:ballY;let cpuCenter=cpuY+ph/2;let dy=targetY-cpuCenter;let move=0;if(abs(dy)>cpuMaxSpeed){move=cpuMaxSpeed*(dy>0?1:-1);}else{move=dy;}cpuY+=move;cpuY=constrain(cpuY,0,h-ph);if(cpuMissCounter>0){cpuMissCounter--;}} 
function updateBall(){ballX+=ballVX;ballY+=ballVY;if(ballY-ballR<0){ballY=ballR;ballVY=-ballVY*restitution;let s=Math.sqrt(ballVX*ballVX+ballVY*ballVY);ballSat=constrain(map(s,0,maxSpeed,minSat,100),minSat,100);}if(ballY+ballR>h){ballY=h-ballR;ballVY=-ballVY*restitution;let s=Math.sqrt(ballVX*ballVX+ballVY*ballVY);ballSat=constrain(map(s,0,maxSpeed,minSat,100),minSat,100);}if(ballVX<0&&ballX-ballR<=playerX+pw&&ballY>=playerY&&ballY<=playerY+ph){ballX=playerX+pw+ballR;ballVX=-ballVX*restitution;let relative=ballY-(playerY+ph/2);let norm=relative/(ph/2);ballVY=norm*5;ballHue=random(0,360);let s=Math.sqrt(ballVX*ballVX+ballVY*ballVY);ballSat=constrain(map(s,0,maxSpeed,minSat,100),minSat,100);}if(ballVX>0&&ballX+ballR>=cpuX&&ballY>=cpuY&&ballY<=cpuY+ph){ballX=cpuX-ballR;ballVX=-ballVX*restitution;let relative=ballY-(cpuY+ph/2);let norm=relative/(ph/2);ballVY=norm*5;ballHue=random(0,360);let s=Math.sqrt(ballVX*ballVX+ballVY*ballVY);ballSat=constrain(map(s,0,maxSpeed,minSat,100),minSat,100);}if(ballX+ballR<0){scoreC++;resetBall();}if(ballX-ballR>w){scoreP++;resetBall();}} 
function drawPaddles(){fill(0,0,100);noStroke();rect(playerX,playerY,pw,ph);rect(cpuX,cpuY,pw,ph);fill(ballHue,ballSat,100);ellipse(ballX,ballY,ballR*2,ballR*2);} 
function drawScores(){fill(0,0,100);text(scoreP,w*0.25,40);text(scoreC,w*0.75,40);} 
function draw(){background(0);handleInput();updateCPU();updateBall();drawPaddles();drawScores();}
